name: DevOps Adventues
author: Pedro Axelrud
markdown: redcarpet
pygments: true
baseurl: /devops-adventues
description: theme for jekyll
github: http://www.github.com/pedroaxl
twitter: http://www.twitter.com/pedroaxl
linkedin: http://www.linkedin.com
email: pedroaxl[at]gmail.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

